name: Node CI

on: [push]

jobs:

  container-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    container:
      image:  node:lts-alpine

    services:
      mongo:
        image: mongo
        ports:
        - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      
      wait-mongo:
        image: waisbrot/wait
        env:
          TARGETS: mongo:${{ job.services.mongo.ports[27017] }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
        MONGO_HOST: mongo
        MONGODB_URI: mongodb://root:example@mongo:${{ job.services.mongo.ports[27017] }}/heroku_dtzf4dns?authSource=admin
